<script src="assets/js/jquery-3.6.0.min.js"></script>
<script src="assets/js/popper.min.js" defer></script>
<script src="assets/js/bootstrap.bundle.min.js" defer></script>
<script src="assets/js/feather.min.js" defer></script>
<script src="assets/plugins/apexchart/apexcharts.min.js" defer></script>
<script src="assets/plugins/apexchart/chart-data.js" defer></script>
<script src="assets/plugins/datatables/jquery.dataTables.min.js" defer></script>
<script src="assets/plugins/datatables/datatables.min.js" defer></script>
<script src="assets/js/select2.min.js" defer></script>
<script src="assets/plugins/amchart/js/core.js" defer></script>
<script src="assets/plugins/amchart/js/charts.js" defer></script>
<script src="assets/plugins/amchart/js/animated.js" defer></script>
<script src="assets/plugins/amchart/js/am-charts.js" defer></script>
<script src="assets/plugins/moment/moment.min.js" defer></script>
<script src="assets/plugins/daterangepicker/daterangepicker.js" defer></script>
<script src="assets/js/jquery.slimscroll.js" defer></script>
<script src="assets/plugins/toastr/toastr.min.js" defer></script>
<script src="assets/plugins/toastr/toastr.js" defer></script>
<script src="assets/js/form-validation.js" defer></script>
<script src="assets/js/app.js" defer></script>
@stack('scripts')
